"""add podcast depot garmin tables (drift catch-up)

Revision ID: a22574149180
Revises: 001
Create Date: 2026-05-31 23:52:13.415213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22574149180'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depot_position',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('wkn', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('last_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('last_price_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day_change_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_change_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('market_symbol', sa.String(length=40), nullable=True),
    sa.Column('price_stale', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depot_snapshot',
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('positions_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garmin_account',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('podcast_prompt',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('prompt_type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garmin_snapshot',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['garmin_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', 'data_type', name='uq_garmin_snapshot_account_date_type')
    )
    op.create_table('podcast_delivery_run',
    sa.Column('delivery_channel', sa.String(length=30), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['podcast_prompt.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcast_feed',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_process_new', sa.Boolean(), nullable=False),
    sa.Column('map_prompt_id', sa.UUID(), nullable=True),
    sa.Column('reduce_prompt_id', sa.UUID(), nullable=True),
    sa.Column('transcription_model', sa.String(length=200), nullable=True),
    sa.Column('summary_model', sa.String(length=200), nullable=True),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_episode_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('min_episode_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('max_audio_size_mb', sa.Integer(), nullable=True),
    sa.Column('keep_audio_days', sa.Integer(), nullable=True),
    sa.Column('ignore_title_patterns', sa.JSON(), nullable=True),
    sa.Column('prefer_external_transcript_url', sa.Boolean(), nullable=False),
    sa.Column('etag', sa.String(length=500), nullable=True),
    sa.Column('last_modified', sa.String(length=500), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_prompt_id'], ['podcast_prompt.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reduce_prompt_id'], ['podcast_prompt.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('podcast_mail_policy',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('target_email', sa.String(length=255), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('feed_filter', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['podcast_prompt.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcast_episode',
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('guid', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('audio_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovery_status', sa.String(length=20), nullable=False),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_class', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_retryable', sa.Boolean(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('chunk_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap_seconds', sa.Integer(), nullable=True),
    sa.Column('chunk_strategy_version', sa.Integer(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('audio_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('summarize_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['podcast_feed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_podcast_episode_feed_guid', 'podcast_episode', ['feed_id', 'guid'], unique=False)
    op.create_index('ix_podcast_episode_processing', 'podcast_episode', ['processing_status', 'locked_at'], unique=False)
    op.create_table('podcast_artifact',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_episode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['podcast_prompt.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_podcast_artifact_active', 'podcast_artifact', ['episode_id', 'artifact_type'], unique=True, postgresql_where='is_active = true')
    op.create_table('podcast_episode_chunk',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('transcript_model', sa.String(length=200), nullable=True),
    sa.Column('map_summary_text', sa.Text(), nullable=True),
    sa.Column('map_summary_model', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_class', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_retryable', sa.Boolean(), nullable=False),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_episode.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'chunk_index', name='uq_chunk_episode_index')
    )
    op.create_table('podcast_delivery_run_episode',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['podcast_artifact.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_episode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['podcast_delivery_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcast_processing_run',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_class', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['podcast_episode_chunk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_episode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['podcast_prompt.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('assistant_message', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('classification_rule', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('classification_rule', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('connector', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('connector_instance', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('digest_policy', sa.Column('digest_prompt', sa.Text(), nullable=True))
    op.add_column('digest_policy', sa.Column('weather_prompt', sa.Text(), nullable=True))
    op.add_column('digest_policy', sa.Column('max_tokens', sa.Integer(), nullable=False))
    op.add_column('digest_policy', sa.Column('since_last_any_digest', sa.Boolean(), nullable=False))
    op.add_column('digest_policy', sa.Column('section_order', sa.Text(), nullable=False))
    op.add_column('digest_policy', sa.Column('include_health', sa.Boolean(), nullable=False))
    op.add_column('digest_policy', sa.Column('health_charts', sa.JSON(), nullable=True))
    op.add_column('digest_policy', sa.Column('health_prompt', sa.Text(), nullable=True))
    op.add_column('digest_policy', sa.Column('health_data_types', sa.JSON(), nullable=True))
    op.add_column('digest_policy', sa.Column('health_days', sa.Integer(), nullable=False))
    op.add_column('digest_policy', sa.Column('include_podcasts', sa.Boolean(), nullable=False))
    op.add_column('digest_policy', sa.Column('include_depot', sa.Boolean(), nullable=False))
    op.add_column('digest_policy', sa.Column('depot_ai_summary', sa.Boolean(), nullable=False))
    op.add_column('digest_policy', sa.Column('depot_prompt', sa.Text(), nullable=True))
    op.add_column('digest_policy', sa.Column('depot_top_n', sa.Integer(), nullable=False))
    op.add_column('digest_policy', sa.Column('depot_days', sa.Integer(), nullable=False))
    op.alter_column('digest_policy', 'max_items',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('digest_policy', 'include_weather',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('digest_policy', 'include_feeds',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('digest_policy', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('digest_policy', 'template',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('digest_run', 'item_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('digest_section', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('forwarding_policy', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('forwarding_policy', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('llm_prompt_version', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('llm_provider_config', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('llm_task', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('llm_task', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('llm_task', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('llm_task', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('llm_task', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('mail_account', sa.Column('sync_folders', sa.Text(), nullable=False))
    op.alter_column('mail_account', 'imap_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mail_account', 'imap_use_ssl',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mail_account', 'smtp_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mail_account', 'smtp_use_tls',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mail_account', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mail_account', 'last_sync_uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mail_classification', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('mail_classification', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mail_classification', 'action_required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mail_classification', 'classified_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('mail_message', sa.Column('tracking_codes', sa.JSON(), nullable=True))
    op.alter_column('mail_message', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mail_message', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mail_message', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('mail_message', 'folder',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_index(op.f('ix_mail_message_account_uid'), table_name='mail_message')
    op.drop_index(op.f('ix_mail_message_is_read'), table_name='mail_message')
    op.create_index('ix_mail_message_account_folder_uid', 'mail_message', ['account_id', 'folder', 'uid'], unique=True)
    op.create_index('ix_mail_message_acct_folder_date', 'mail_message', ['account_id', 'folder', 'date'], unique=False)
    op.alter_column('rss_feed', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('rss_feed', 'fetch_interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rss_item', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('weather_source', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('weather_source', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_source', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('weather_source', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rss_item', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('rss_feed', 'fetch_interval_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rss_feed', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_mail_message_acct_folder_date', table_name='mail_message')
    op.drop_index('ix_mail_message_account_folder_uid', table_name='mail_message')
    op.create_index(op.f('ix_mail_message_is_read'), 'mail_message', ['is_read'], unique=False)
    op.create_index(op.f('ix_mail_message_account_uid'), 'mail_message', ['account_id', 'uid'], unique=True)
    op.alter_column('mail_message', 'folder',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('mail_message', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mail_message', 'is_flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mail_message', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('mail_message', 'tracking_codes')
    op.alter_column('mail_classification', 'classified_by',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('mail_classification', 'action_required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mail_classification', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mail_classification', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('mail_account', 'last_sync_uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mail_account', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mail_account', 'smtp_use_tls',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mail_account', 'smtp_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mail_account', 'imap_use_ssl',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('mail_account', 'imap_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('mail_account', 'sync_folders')
    op.alter_column('llm_task', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('llm_task', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('llm_task', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('llm_task', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('llm_task', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('llm_provider_config', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('llm_prompt_version', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('forwarding_policy', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('forwarding_policy', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('digest_section', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('digest_run', 'item_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('digest_policy', 'template',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('digest_policy', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('digest_policy', 'include_feeds',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('digest_policy', 'include_weather',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('digest_policy', 'max_items',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('digest_policy', 'depot_days')
    op.drop_column('digest_policy', 'depot_top_n')
    op.drop_column('digest_policy', 'depot_prompt')
    op.drop_column('digest_policy', 'depot_ai_summary')
    op.drop_column('digest_policy', 'include_depot')
    op.drop_column('digest_policy', 'include_podcasts')
    op.drop_column('digest_policy', 'health_days')
    op.drop_column('digest_policy', 'health_data_types')
    op.drop_column('digest_policy', 'health_prompt')
    op.drop_column('digest_policy', 'health_charts')
    op.drop_column('digest_policy', 'include_health')
    op.drop_column('digest_policy', 'section_order')
    op.drop_column('digest_policy', 'since_last_any_digest')
    op.drop_column('digest_policy', 'max_tokens')
    op.drop_column('digest_policy', 'weather_prompt')
    op.drop_column('digest_policy', 'digest_prompt')
    op.alter_column('connector_instance', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('connector', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('classification_rule', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('classification_rule', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assistant_message', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('podcast_processing_run')
    op.drop_table('podcast_delivery_run_episode')
    op.drop_table('podcast_episode_chunk')
    op.drop_index('ix_podcast_artifact_active', table_name='podcast_artifact', postgresql_where='is_active = true')
    op.drop_table('podcast_artifact')
    op.drop_index('ix_podcast_episode_processing', table_name='podcast_episode')
    op.drop_index('ix_podcast_episode_feed_guid', table_name='podcast_episode')
    op.drop_table('podcast_episode')
    op.drop_table('podcast_mail_policy')
    op.drop_table('podcast_feed')
    op.drop_table('podcast_delivery_run')
    op.drop_table('garmin_snapshot')
    op.drop_table('podcast_prompt')
    op.drop_table('garmin_account')
    op.drop_table('depot_snapshot')
    op.drop_table('depot_position')
    # ### end Alembic commands ###
